#! /bin/bash

set -x

jar=$(ls ${OPENSHIFT_REPO_DIR}target/*.war | head -n1)


export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_40
export PATH=$JAVA_HOME/bin:$PATH


#nohup java -server \
#     -jar ${jar} \
#     --spring.profiles.active=prod \
#     --server.address=${OPENSHIFT_DIY_IP} \
#     --server.port=${OPENSHIFT_DIY_PORT} \
#     --spring.datasource.url=jdbc:mysql://${OPENSHIFT_MYSQL_DB_HOST}:${OPENSHIFT_MYSQL_DB_PORT}/${OPENSHIFT_APP_NAME} \
#     --spring.datasource.username=${OPENSHIFT_MYSQL_DB_USERNAME} \
#     --spring.datasource.password=${OPENSHIFT_MYSQL_DB_PASSWORD} > ${OPENSHIFT_DIY_LOG_DIR}fantacalcio.log 2>&1 &

nohup java -Xms384m -Xmx384m \
     -jar ${jar} \
     --spring.profiles.active=dev \
     --server.address=${OPENSHIFT_DIY_IP} \
     --server.port=${OPENSHIFT_DIY_PORT} \
     --spring.datasource.driver-class-name=org.h2.jdbcx.JdbcDataSource \
     --spring.datasource.url=jdbc:h2:${OPENSHIFT_DATA_DIR}\fantadb;DB_CLOSE_DELAY=-1 \
     --spring.datasource.username=sa \
     --spring.datasource.password=t > ${OPENSHIFT_DIY_LOG_DIR}fantacalcio.log 2>&1 &
